import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals

// Тема 7: data class - особенности и ограничения.

// data class автоматически генерирует equals/hashCode/toString/copy/componentN
// по свойствам ИЗ PRIMARY CONSTRUCTOR. Нужен хотя бы один параметр, все - val/var.
// Ограничения: data class не может быть abstract, open, sealed или inner.
data class Money(val amount: Int, val currency: String) {
    // Свойство, объявленное в теле класса (не в primary constructor),
    // НЕ участвует в equals/hashCode/toString/copy/componentN.
    var comment: String = ""
}

class DataClassTest {

    @Test
    fun autoGeneratedEqualsHashCodeToString() {
        val a = Money(100, "USD")
        val b = Money(100, "USD")

        assertEquals(a, b) // equals сгенерирован по всем полям primary constructor
        assertEquals(a.hashCode(), b.hashCode())
        assertEquals("Money(amount=100, currency=USD)", a.toString())
    }

    @Test
    fun copyChangesOnlySelectedFields() {
        val a = Money(100, "USD")
        val b = a.copy(amount = 200) // остальные поля копируются как есть

        assertEquals(200, b.amount)
        assertEquals("USD", b.currency)
    }

    @Test
    fun destructuringUsesComponentFunctions() {
        val (amount, currency) = Money(100, "USD")
        assertEquals(100, amount)
        assertEquals("USD", currency)
    }

    @Test
    fun bodyPropertiesAreIgnoredByGeneratedMembers() {
        val a = Money(100, "USD").apply { comment = "first" }
        val b = Money(100, "USD").apply { comment = "second" }

        // comment не в primary constructor - equals его не учитывает.
        assertEquals(a, b)
        assertNotEquals(a.comment, b.comment)
    }
}
